# Please don't modify this file, without first checking if it makes sense to
# adopt for most other Kapost projects. Ideally, we would keep these files as
# similar as possible to ease maintainability. Instead, open a PR in the
# codeclimate-common repo at https://github.com/kapost/codeclimate-common

---
version: 2
plugins:
  rubocop:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    exclude_patterns:
    - "**/*Spec.js"
    - "**/*_spec.rb"
    - "**/specs/"
    - "**/spec/"
    - "spec/"
    - "**/tests/"
    - "**/test/"
    - "test/"
    - "features/"
    - "lib/tasks/"
    - "tasks/"
    config:
      languages:
        javascript:
          mass_threshold: 140
        ruby:
          mass_threshold: 25 # default in source code as of 01/18/2018 (docs out of date)
  reek:
    enabled: true
  shellcheck:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
  csslint:
    enabled: false
  scss-lint:
    enabled: true
  coffeelint:
    enabled: false
  eslint:
    enabled: true
    channel: "eslint-6"
    config:
      extensions:
      - .es6
      - .js
      - .jsx
    checks:
      keyword-spacing:
        enabled: false
      react/jsx-space-before-closing:
        enabled: false
      no-warning-comments: # these are nice for client
        enabled: false
  nodesecurity:
    enabled: false # turn back on if they start supporting yarn.lock
  grep:
    enabled: true
    exclude_patterns:
    - "**/spec_helper.rb"
    config:
      patterns:
        no-dot-only:
          pattern: (describe|context|it)\.only
          annotation: "Make sure not to commit `.only` in specs, as it disables the rest of the suite."
          severity: blocker
          path_patterns:
          - "**/*Spec.js"
          - "**/specs/*.js"
          - "**/spec/*.js"
          - "spec/*.js"
          - "**/tests/*.js"
          - "**/test/*.js"
          - "test/*.js"
        no-focused-specs:
          pattern: "(focus: true|:focus => true|fit \")"
          annotation: "Make sure not to commit focused ruby specs (`focus: true` or `fit`), as it disables the rest of the suite."
          severity: blocker
          path_patterns:
          - "**/*_spec.rb"
          - "**/specs/*.rb"
          - "**/spec/*.rb"
          - "spec/*.rb"
          - "**/tests/*.rb"
          - "**/test/*.rb"
          - "test/*.rb"


exclude_patterns:
  - "**/vendor/"
  - "**/node_modules/"
  - "build/"
  - "index.js"
  - "Gulpfile.js"
  - "bin/"
  - "config/"
  - "coverage/"
  - "dist/"
  - "transpiled/"
  - "test/**/*"
  - "**/*.md"
  - "**/*.json"
  - "**/*.svg"
  - "**/fixtures/*"
  - "**/fixture/*"
  - "**/*Fixture.js"
  - "**_meyerReset.scss"
  - "docker/"
  - "scripts/"
  - "app/assets/static/static/*" # change to just assets when we move scss into pods
  - "app/assets/static/svg/*" # change to just assets when we move scss into pods
  - ".codeclimate.yml"
  - "db/migrate/*"
  - "engines/**/db/migrate/*"
  - "spec/fixtures/*"
  - "features/"
  - "Guardfile"
  - "Rakefile"
  - "config.reek"
  - "**/webpack.config.js"
  - "**/webpack.config.spec.js"
  - "**/.eslintrc.js"
  - "app/assets/javascripts/**/*"
