# Please don't modify this file, without first checking if it makes sense to
# adopt for most other Kapost projects. Ideally, we would keep these files as
# similar as possible to ease maintainability. Instead, open a PR in the
# codeclimate-common repo at https://github.com/kapost/codeclimate-common

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "bin/**/*"
    - "script/**/*"
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "**/spec/**/*"
    - "**/test/**/*"
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "**/spec/**/*"
    - "**/test/**/*"
Style/AndOr:
  EnforcedStyle: conditionals
Layout/CaseIndentation:
  IndentOneStep: true
Style/Documentation:
  Enabled: false
  Exclude:
    - "**/spec/**/*"
    - "**/test/**/*"
Style/EachWithObject:
  Enabled: false
Style/HashSyntax:
  Exclude:
    - "lib/tasks/**/*"
Style/SymbolArray:
  EnforcedStyle: brackets
Layout/LineLength:
  Max: 120
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"
    "%W": "[]"
    "%i": "[]"
    "%I": "[]"
    "%r": "()"
Style/RegexpLiteral:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
# These are better handled by reek
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false

# Rubocop's global exclude seems to fail to exclude the bin/ dir, so set all
# the cops that are failing manually, since most of these files are
# auto-generated anyways. Also, if the rules also appear above, we need to copy
# the same attrs, because YAML won't merge, only overwrite.

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - "bin/**/*"
Style/FrozenStringLiteralComment:
  Exclude:
    - "bin/**/*"
Layout/LeadingCommentSpace:
  Exclude:
    - "bin/**/*"
Layout/SpaceInsideParens:
  Exclude:
    - "bin/**/*"
Layout/ParameterAlignment:
  Exclude:
    - "bin/**/*"
Layout/ExtraSpacing:
  Exclude:
    - "config/routes.rb"
    - "bin/**/*"
Style/WordArray:
  EnforcedStyle: brackets
Lint/PercentStringArray:
  Exclude:
    # SecureHeaders needs the single quotes in `%w[https: 'self']`
    - config/initializers/secure_headers.rb
# We prefer using raise everywhere.
Style/SignalException:
  Description: "Checks for proper usage of fail and raise."
  Enabled: false
Style/SafeNavigation:
  AutoCorrect: false # safe navigation autocorrect can easily create bad logic
