# Please don't modify this file, without first checking if it makes sense to
# adopt for most other Kapost projects. Ideally, we would keep these files as
# similar as possible to ease maintainability. Instead, open a PR in the
# codeclimate-common repo at https://github.com/kapost/codeclimate-common

Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - "**/Rakefile"
    - "**/config.ru"
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "bin/**/*"
    - "script/**/*"

Metrics/LineLength:
  Max: 120
Rails/Date:
  Enabled: false
Rails/TimeZone:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.3
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"
Style/AndOr:
  EnforcedStyle: conditionals
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
Layout/CaseIndentation:
  IndentOneStep: true
Style/Documentation:
  Enabled: true
Style/EachWithObject:
  Enabled: false
Style/HashSyntax:
  Exclude:
    - "lib/tasks/**/*"
Style/SymbolArray:
  EnforcedStyle: brackets
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"
    "%W": "[]"
    "%i": "[]"
    "%I": "[]"
    "%r": "()"
Style/SignalException:
  EnforcedStyle: semantic
Style/SingleLineBlockParams:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Layout/MultilineMethodCallIndentation:
  Exclude:
    - "spec/**/*.rb"

# These are better handled by reek
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false

# Rubocop's global exclude seems to fail to exclude the bin/ dir, so set all
# the cops that are failing manually, since most of these files are
# auto-generated anyways. Also, if the rules also appear above, we need to copy
# the same attrs, because YAML won't merge, only overwrite.

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - "bin/**/*"
Style/FrozenStringLiteralComment:
  Exclude:
    - "bin/**/*"
Layout/LeadingCommentSpace:
  Exclude:
    - "bin/**/*"
Layout/SpaceInsideParens:
  Exclude:
    - "bin/**/*"
Layout/AlignParameters:
  Exclude:
    - "bin/**/*"
Layout/ExtraSpacing:
  Exclude:
    - "config/routes.rb"
    - "bin/**/*"
  Exclude:
    - "config/routes.rb"
Style/WordArray:
  EnforcedStyle: brackets
Lint/PercentStringArray:
  Exclude:
    # SecureHeaders needs the single quotes in `%w[https: 'self']`
    - config/initializers/secure_headers.rb
# We prefer using raise everywhere.
Style/SignalException:
  Description: "Checks for proper usage of fail and raise."
  Enabled: false
Style/SafeNavigation:
  AutoCorrect: false # safe navigation autocorrect can easily create bad logic
Style/RegexpLiteral:
  AllowInnerSlashes: true
  EnforcedStyle: slashes
